### ISSUE TITLE
拍照功能

### ISSUE THREAD

**Issue by xiangxm** [MannaYang/AudioVideoCodec#1]
请问博主是否会考虑加入拍照功能？

**Comment by MannaYang** [comment]
拍照计划是以OpenGL ES+滤镜的方式，展示方式分2种：1.拍照页面底部列表选择滤镜  2. 拍照页面右上角魔法棒弹出滤镜列表，你如果需要急用，可在CameraManager管理类中添加takePhoto方法，或是自定义CameraPreview等，目前还在研究滤镜，大概需要几周时间添加这个功能

**Comment by MannaYang** [comment]
> 请问博主是否会考虑加入拍照功能？

拍照计划是以OpenGL ES+滤镜的方式，展示方式分2种：1.拍照页面底部列表选择滤镜 2. 拍照页面右上角魔法棒弹出滤镜列表，你如果需要急用，可在CameraManager管理类中添加takePhoto方法，或是自定义CameraPreview等，目前还在研究滤镜，大概需要几周时间添加这个功能

**Comment by xiangxm** [comment]
好的，非常感谢。
