### ISSUE TITLE
怎么能暂停再录制？

### ISSUE THREAD

**Issue by ZhuoJunErGe** [MannaYang/AudioVideoCodec#2]
录制-->关闭-->录制-->关闭-->录制-->关闭
多次重复后得到的视频少于重复次数

**Comment by MannaYang** [comment]
你是想往一个视频文件写入，而非生成多段视频录制文件然后再合并成一个视频文件？发自我的华为手机-------- 原始邮件 --------发件人： ZhuoJunErGe <notifications@github.com>日期： 2020年12月23日周三 17:30收件人： MannaYang/AudioVideoCodec <AudioVideoCodec@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [MannaYang/AudioVideoCodec] 怎么能暂停再录制？ (#2)

录制-->关闭-->录制-->关闭-->录制-->关闭

多次重复后得到的视频少于重复次数

**Comment by ZhuoJunErGe** [comment]
已经找到原因的，文件创建的是用的分钟，改成毫秒值就好了
